const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv");
const connectDB = require("./config/db");
dotenv.config();
const app = express();
app.use(cors({ origin: true }));
app.use(express.json());
connectDB();
app.get("/", (req, res) => res.json({ ok: true }));
app.use("/api/auth", require("./routes/auth"));
app.use("/api/trips", require("./routes/trips"));
app.use("/api/planner", require("./routes/planner"));
const PORT = process.env.PORT || 5000;
app.listen(PORT, ()=>console.log(`Server listening on ${PORT}`));
